/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ActivityView, AgentSeatContextSync, ApproveOutputRequest, ConversationView, GeneratePlansRequest, GeneratePlansValue, KnowledgeView, ListKnowledgeRequest, ListMessagesRequest, ListSkillsRequest, MessageView, OutputView, RoleView, SeatView, SendInstructionRequest, SimulatorView, SkillView, SubmitOutputRequest, TaskView } from '@deepseek-ai/dsh-wargame-platform/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$77617267616d65 {
    approveOutput: (request: ApproveOutputRequest) => Promise<RemoteResult<OutputView>>
    confirmPlan: () => Promise<RemoteResult<{ confirmed: true; }>>
    generatePlans: (request: GeneratePlansRequest) => Promise<RemoteResult<GeneratePlansValue>>
    listActivities: () => Promise<RemoteResult<ActivityView[]>>
    listConversations: () => Promise<RemoteResult<ConversationView[]>>
    listKnowledge: (request: ListKnowledgeRequest) => Promise<RemoteResult<KnowledgeView[]>>
    listMessages: (request: ListMessagesRequest) => Promise<RemoteResult<MessageView[]>>
    listPendingOutputs: () => Promise<RemoteResult<OutputView[]>>
    listRoles: () => Promise<RemoteResult<RoleView[]>>
    listSeats: () => Promise<RemoteResult<SeatView[]>>
    listSimulators: () => Promise<RemoteResult<SimulatorView[]>>
    listSkills: (request: ListSkillsRequest) => Promise<RemoteResult<SkillView[]>>
    listTasks: () => Promise<RemoteResult<TaskView[]>>
    rejectOutput: (request: ApproveOutputRequest) => Promise<RemoteResult<OutputView>>
    sendInstruction: (request: SendInstructionRequest) => Promise<RemoteResult<TaskView>>
    setAgentSeatContext: (request: AgentSeatContextSync) => Promise<RemoteResult<{ synced: true; }>>
    submitOutput: (request: SubmitOutputRequest) => Promise<RemoteResult<OutputView>>
  }
  interface TypertRemoteMap {
    'wargame/approveOutput': (request: ApproveOutputRequest) => Promise<RemoteResult<OutputView>>
    'wargame/confirmPlan': () => Promise<RemoteResult<{ confirmed: true; }>>
    'wargame/generatePlans': (request: GeneratePlansRequest) => Promise<RemoteResult<GeneratePlansValue>>
    'wargame/listActivities': () => Promise<RemoteResult<ActivityView[]>>
    'wargame/listConversations': () => Promise<RemoteResult<ConversationView[]>>
    'wargame/listKnowledge': (request: ListKnowledgeRequest) => Promise<RemoteResult<KnowledgeView[]>>
    'wargame/listMessages': (request: ListMessagesRequest) => Promise<RemoteResult<MessageView[]>>
    'wargame/listPendingOutputs': () => Promise<RemoteResult<OutputView[]>>
    'wargame/listRoles': () => Promise<RemoteResult<RoleView[]>>
    'wargame/listSeats': () => Promise<RemoteResult<SeatView[]>>
    'wargame/listSimulators': () => Promise<RemoteResult<SimulatorView[]>>
    'wargame/listSkills': (request: ListSkillsRequest) => Promise<RemoteResult<SkillView[]>>
    'wargame/listTasks': () => Promise<RemoteResult<TaskView[]>>
    'wargame/rejectOutput': (request: ApproveOutputRequest) => Promise<RemoteResult<OutputView>>
    'wargame/sendInstruction': (request: SendInstructionRequest) => Promise<RemoteResult<TaskView>>
    'wargame/setAgentSeatContext': (request: AgentSeatContextSync) => Promise<RemoteResult<{ synced: true; }>>
    'wargame/submitOutput': (request: SubmitOutputRequest) => Promise<RemoteResult<OutputView>>
  }
  interface TypertRemoteNamespaceMap {
    'wargame': TypertRemoteNamespace$77617267616d65
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
