/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_wargame_platform_wargame_approveOutput_parameter_0$schema = z.object({
  'outputId': z.string(),
  'bySeatId': z.string(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_approveOutput_result$schema = z.object({
  'id': z.string(),
  'taskId': z.string(),
  'seatId': z.string(),
  'content': z.string(),
  'status': z.union([z.literal("completed"), z.literal("executing"), z.literal("waiting_approval")]),
})
const _deepseek_ai_dsh_wargame_platform_wargame_confirmPlan_result$schema = z.object({
  'confirmed': z.literal(true),
})
const _deepseek_ai_dsh_wargame_platform_wargame_generatePlans_parameter_0$schema = z.object({
  'topic': z.string(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_generatePlans_result$schema = z.object({
  'plans': z.array(z.object({
  'planId': z.string(),
  'planName': z.string(),
  'content': z.string(),
  'seatId': z.string(),
  'weightedScore': z.number(),
  'rank': z.number(),
  'outcomes': z.array(z.object({
  'simulatorId': z.string(),
  'connected': z.boolean(),
  'score': z.number().optional(),
})),
  'confirmed': z.boolean(),
})),
  'report': z.string(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_listActivities_result$schema = z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'phases': z.array(z.string()),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_listConversations_result$schema = z.array(z.object({
  'id': z.string(),
  'type': z.union([z.literal("group"), z.literal("direct")]),
  'members': z.array(z.string()),
  'activityId': z.string(),
  'branchFrom': z.string().optional(),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_listKnowledge_parameter_0$schema = z.object({
  'roleId': z.string(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_listKnowledge_result$schema = z.array(z.object({
  'id': z.string(),
  'title': z.string(),
  'content': z.string(),
  'clearance': z.number(),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_listMessages_parameter_0$schema = z.object({
  'conversationId': z.string(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_listMessages_result$schema = z.array(z.object({
  'id': z.string(),
  'conversationId': z.string(),
  'type': z.union([z.literal("instruction"), z.literal("report"), z.literal("proactive"), z.literal("pending_output")]),
  'from': z.string(),
  'content': z.string(),
  'mentions': z.array(z.string()),
  'timestamp': z.number(),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_listPendingOutputs_result$schema = z.array(z.object({
  'id': z.string(),
  'taskId': z.string(),
  'seatId': z.string(),
  'content': z.string(),
  'status': z.union([z.literal("completed"), z.literal("executing"), z.literal("waiting_approval")]),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_listRoles_result$schema = z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'level': z.number(),
  'clearance': z.number(),
  'canDispatch': z.boolean(),
  'canApprove': z.boolean(),
  'packs': z.array(z.string()),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_listSeats_result$schema = z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'roleId': z.string(),
  'roleName': z.string(),
  'level': z.number(),
  'clearance': z.number(),
  'canDispatch': z.boolean(),
  'canApprove': z.boolean(),
  'parentId': z.union([z.literal(null), z.string()]),
  'status': z.union([z.literal("idle"), z.literal("executing"), z.literal("awaiting")]),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_listSimulators_result$schema = z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'weight': z.number(),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_listSkills_parameter_0$schema = z.object({
  'roleId': z.string(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_listSkills_result$schema = z.array(z.object({
  'name': z.string(),
  'description': z.string(),
  'clearance': z.number(),
  'enabled': z.boolean(),
  'allowedRoles': z.array(z.string()),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_listTasks_result$schema = z.array(z.object({
  'id': z.string(),
  'activityId': z.string(),
  'title': z.string(),
  'requiredSkills': z.array(z.string()),
  'requiredClearance': z.number(),
  'assignedSeatId': z.string().optional(),
  'status': z.union([z.literal("pending"), z.literal("executing"), z.literal("done")]),
}))
const _deepseek_ai_dsh_wargame_platform_wargame_rejectOutput_parameter_0$schema = z.object({
  'outputId': z.string(),
  'bySeatId': z.string(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_rejectOutput_result$schema = z.object({
  'id': z.string(),
  'taskId': z.string(),
  'seatId': z.string(),
  'content': z.string(),
  'status': z.union([z.literal("completed"), z.literal("executing"), z.literal("waiting_approval")]),
})
const _deepseek_ai_dsh_wargame_platform_wargame_sendInstruction_parameter_0$schema = z.object({
  'activityId': z.string(),
  'text': z.string(),
  'bySeatId': z.string().optional(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_sendInstruction_result$schema = z.object({
  'id': z.string(),
  'activityId': z.string(),
  'title': z.string(),
  'requiredSkills': z.array(z.string()),
  'requiredClearance': z.number(),
  'assignedSeatId': z.string().optional(),
  'status': z.union([z.literal("pending"), z.literal("executing"), z.literal("done")]),
})
const _deepseek_ai_dsh_wargame_platform_wargame_setAgentSeatContext_parameter_0$schema = z.object({
  'sessionId': z.string(),
  'token': z.string(),
  'userId': z.string(),
  'userName': z.string(),
  'activityId': z.string(),
  'activityName': z.string(),
  'seatId': z.string(),
  'seatName': z.string(),
  'roleId': z.string(),
  'roleName': z.string(),
  'clearance': z.number(),
  'canDispatch': z.boolean(),
  'canApprove': z.boolean(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_setAgentSeatContext_result$schema = z.object({
  'synced': z.literal(true),
})
const _deepseek_ai_dsh_wargame_platform_wargame_submitOutput_parameter_0$schema = z.object({
  'taskId': z.string(),
  'seatId': z.string(),
  'content': z.string(),
})
const _deepseek_ai_dsh_wargame_platform_wargame_submitOutput_result$schema = z.object({
  'id': z.string(),
  'taskId': z.string(),
  'seatId': z.string(),
  'content': z.string(),
  'status': z.union([z.literal("completed"), z.literal("executing"), z.literal("waiting_approval")]),
})

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-wargame-platform',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/approveOutput',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'approveOutput',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#ApproveOutputRequest',
            schema: _deepseek_ai_dsh_wargame_platform_wargame_approveOutput_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#OutputView',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_approveOutput_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":224,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/confirmPlan',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'confirmPlan',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/confirmPlan:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_confirmPlan_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":266,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/generatePlans',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'generatePlans',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#GeneratePlansRequest',
            schema: _deepseek_ai_dsh_wargame_platform_wargame_generatePlans_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#GeneratePlansValue',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_generatePlans_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":238,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listActivities',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listActivities',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listActivities:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listActivities_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":103,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listConversations',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listConversations',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listConversations:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listConversations_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":160,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listKnowledge',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listKnowledge',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#ListKnowledgeRequest',
            schema: _deepseek_ai_dsh_wargame_platform_wargame_listKnowledge_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listKnowledge:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listKnowledge_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":114,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listMessages',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listMessages',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#ListMessagesRequest',
            schema: _deepseek_ai_dsh_wargame_platform_wargame_listMessages_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listMessages:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listMessages_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":171,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listPendingOutputs',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listPendingOutputs',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listPendingOutputs:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listPendingOutputs_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":202,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listRoles',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listRoles',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listRoles:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listRoles_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":89,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listSeats',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listSeats',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listSeats:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listSeats_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":83,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listSimulators',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listSimulators',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listSimulators:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listSimulators_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":149,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listSkills',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listSkills',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#ListSkillsRequest',
            schema: _deepseek_ai_dsh_wargame_platform_wargame_listSkills_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listSkills:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listSkills_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":128,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/listTasks',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'listTasks',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/listTasks:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_listTasks_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":186,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/rejectOutput',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'rejectOutput',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#ApproveOutputRequest',
            schema: _deepseek_ai_dsh_wargame_platform_wargame_rejectOutput_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#OutputView',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_rejectOutput_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":230,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/sendInstruction',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'sendInstruction',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#SendInstructionRequest',
            schema: _deepseek_ai_dsh_wargame_platform_wargame_sendInstruction_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#TaskView',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_sendInstruction_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":207,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/setAgentSeatContext',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'setAgentSeatContext',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#AgentSeatContextSync',
            schema: _deepseek_ai_dsh_wargame_platform_wargame_setAgentSeatContext_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform#wargame/setAgentSeatContext:result',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_setAgentSeatContext_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":73,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-wargame-platform#wargame/submitOutput',
      service: 'wargamePlatform',
      namespace: 'wargame',
      method: 'submitOutput',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#SubmitOutputRequest',
            schema: _deepseek_ai_dsh_wargame_platform_wargame_submitOutput_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-wargame-platform/types#OutputView',
        schema: _deepseek_ai_dsh_wargame_platform_wargame_submitOutput_result$schema,
      },
      sourceLocation: {"file":"packages/platform/wargame-platform/src/index.ts","line":218,"column":3},
    },
  ],
}

export default TYPERT_REMOTE
